### ISSUE TITLE
Bluetooth 5.3 Adapter CM591; ATS2851

### ISSUE THREAD

**Issue by SaschaVasarrhelyi** [jeremyb31/bluetooth-6.2#2]
Hi,
since i installed the Patch, the dongel dosn't schow up anymore in Blueman-Manager.

**Comment by jeremyb31** [comment]
Post results from terminal for 
lsusb; uname -r

**Comment by SaschaVasarrhelyi** [comment]
$ lsusb; uname -r
Bus 007 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 003 Device 009: ID 2412:1812 YICHIP Wireless Mouse
Bus 003 Device 008: ID 25a7:0701 Areson Technology Corp SPEEDLINK LUCIDIS Wireless Deskset
Bus 003 Device 007: ID 1a40:0101 Terminus Technology Inc. Hub
Bus 003 Device 004: ID 1a40:0101 Terminus Technology Inc. Hub
Bus 003 Device 002: ID 3c45:6366 Sonix Technology Co., Ltd. QHD Webcam
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 006 Device 003: ID 0b05:190e ASUSTek Computer, Inc. ASUS USB-BT500
Bus 006 Device 002: ID 10d7:b012 Actions general adapter
Bus 006 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 005 Device 002: ID 0a12:0001 Cambridge Silicon Radio, Ltd Bluetooth Dongle (HCI mode)
Bus 005 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 002 Device 002: ID 04a9:176d Canon, Inc. PIXMA MG2500 Series
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 004 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 001 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 011 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 010 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 009 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 008 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
6.2.0-33-generic

I think the "Bus 006 Device 002: ID 10d7:b012 Actions general adapter" is the UGREEN Bluetooth 5.3 Adapter.

**Comment by jeremyb31** [comment]
There isn't a patch in this that affects the UGREEN adapter

**Comment by SaschaVasarrhelyi** [comment]
Oh, i have search on this website before i came to youre website https://forums.linuxmint.com/viewtopic.php?t=404582 so my question: is there a patch for the adapter in the Bluetooth 5.15.git on youre repo?
I have the Problem that i don't understand to patch my kernel with the newest Bluetooth-next patches and on the Mint-Page above the install of youre patches are pretty easy on this mint-page.

**Comment by jeremyb31** [comment]
You might want to install the 6.5.5 kernel and see if the Bluetooth works

**Comment by SaschaVasarrhelyi** [comment]
Thank You very much for this,
i will take a chance on kernel 6.5.5
